trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  # - task: UseRubyVersion@0
  #   inputs:
  #     versionSpec: ">= 2.6"

  - script: |
      sudo apt-get install ruby-full build-essential zlib1g-dev
    displayName: "Install Package"

  - script: |
      sudo echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
      sudo echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
      sudo echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
      sudo source ~/.bashrc
    displayName: "Config gem"

  - script: |
      sudo gem install jekyll bundler
    displayName: "Install jekyll"

  - script: |
      sudo jekyll build
    displayName: "Jekyll buils"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'