trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: ">= 2.6"

  - script: |
      gem install jekyll bundler
      bundle install --retry=3 --jobs=4          
    displayName: "Install Jekyll"

  - script: |
      bundle install
      jekyll -v
      jekyll build          
    displayName: "Build Jekyll Site"