trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: ">= 2.6"

  - script: |
      apt-get install ruby-full build-essential zlib1g-dev
    displayName: "Install Package"

  - script: |
      echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
      echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
      echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
      source ~/.bashrc
    displayName: "Config gem"

  - script: |
      gem install jekyll bundler
    displayName: "Install jekyll"

  - script: |
      jekyll build
    displayName: "Jekyll buils"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'